### Listar productos
GET  http://localhost:3000/producto

### Crear producto
POST http://localhost:3000/producto
Content-Content-Type: aplication/json
{
    "nombre":"impresora laser",
    "precio":"500.95",
    "stock":12,
    "categoriaId":1
}